export type Place = {
  city: string;
  region: string;
  lat: number;
  lng: number;
};

/** Approximate public headquarters. Not part of the models.dev catalog. */
const places: Record<string, Place> = {
  openai: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  anthropic: { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.41 },
  google: { city: "Mountain View", region: "United States", lat: 37.42, lng: -122.08 },
  "google-vertex": { city: "Mountain View", region: "United States", lat: 37.41, lng: -122.09 },
  xai: { city: "Palo Alto", region: "United States", lat: 37.44, lng: -122.14 },
  meta: { city: "Menlo Park", region: "United States", lat: 37.45, lng: -122.18 },
  groq: { city: "Mountain View", region: "United States", lat: 37.4, lng: -122.07 },
  cerebras: { city: "Sunnyvale", region: "United States", lat: 37.37, lng: -122.03 },
  fireworks: { city: "Redwood City", region: "United States", lat: 37.49, lng: -122.23 },
  "fireworks-ai": { city: "Redwood City", region: "United States", lat: 37.49, lng: -122.23 },
  together: { city: "San Francisco", region: "United States", lat: 37.77, lng: -122.42 },
  "togetherai": { city: "San Francisco", region: "United States", lat: 37.77, lng: -122.42 },
  perplexity: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.39 },
  nvidia: { city: "Santa Clara", region: "United States", lat: 37.37, lng: -121.96 },
  databricks: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  "amazon-bedrock": { city: "Seattle", region: "United States", lat: 47.62, lng: -122.33 },
  azure: { city: "Redmond", region: "United States", lat: 47.67, lng: -122.12 },
  "github-copilot": { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.4 },
  huggingface: { city: "New York", region: "United States", lat: 40.74, lng: -73.99 },
  cohere: { city: "Toronto", region: "Canada", lat: 43.65, lng: -79.38 },
  mistral: { city: "Paris", region: "Europe", lat: 48.86, lng: 2.35 },
  ai21: { city: "Tel Aviv", region: "Israel", lat: 32.07, lng: 34.79 },
  deepseek: { city: "Hangzhou", region: "China", lat: 30.27, lng: 120.15 },
  alibaba: { city: "Hangzhou", region: "China", lat: 30.28, lng: 120.16 },
  "alibaba-cn": { city: "Hangzhou", region: "China", lat: 30.26, lng: 120.14 },
  moonshot: { city: "Beijing", region: "China", lat: 39.9, lng: 116.4 },
  moonshotai: { city: "Beijing", region: "China", lat: 39.9, lng: 116.4 },
  "zhipuai": { city: "Beijing", region: "China", lat: 39.91, lng: 116.41 },
  zai: { city: "Beijing", region: "China", lat: 39.92, lng: 116.39 },
  baidu: { city: "Beijing", region: "China", lat: 39.99, lng: 116.32 },
  minimax: { city: "Shanghai", region: "China", lat: 31.23, lng: 121.47 },
  // Providers and gateways
  vercel: { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.39 },
  "cloudflare-ai-gateway": { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.39 },
  poe: { city: "Mountain View", region: "United States", lat: 37.39, lng: -122.08 },
  "perplexity-agent": { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.39 },
  deepinfra: { city: "Palo Alto", region: "United States", lat: 37.44, lng: -122.16 },
  baseten: { city: "San Francisco", region: "United States", lat: 37.77, lng: -122.41 },
  openrouter: { city: "New York", region: "United States", lat: 40.72, lng: -74.0 },
  wandb: { city: "Livingston, NJ", region: "United States", lat: 40.79, lng: -74.32 },
  watsonx: { city: "Armonk, NY", region: "United States", lat: 41.13, lng: -73.71 },
  nebius: { city: "Amsterdam", region: "Europe", lat: 52.37, lng: 4.9 },
  stackit: { city: "Neckarsulm", region: "Europe", lat: 49.19, lng: 9.22 },
  evroc: { city: "Stockholm", region: "Europe", lat: 59.33, lng: 18.07 },
  "cloudferro-sherlock": { city: "Warsaw", region: "Europe", lat: 52.23, lng: 21.01 },
  siliconflow: { city: "Beijing", region: "China", lat: 39.98, lng: 116.31 },
  "qiniu-ai": { city: "Shanghai", region: "China", lat: 31.2, lng: 121.5 },
  // Labs beyond the first fourteen: well-known public headquarters, plus a few looked up September 2026.
  "bytedance-seed": { city: "Beijing", region: "China", lat: 39.98, lng: 116.31 },
  xiaomi: { city: "Beijing", region: "China", lat: 40.05, lng: 116.3 },
  amazon: { city: "Seattle", region: "United States", lat: 47.62, lng: -122.34 },
  microsoft: { city: "Redmond", region: "United States", lat: 47.64, lng: -122.13 },
  ibm: { city: "Armonk, NY", region: "United States", lat: 41.11, lng: -73.72 },
  tencent: { city: "Shenzhen", region: "China", lat: 22.54, lng: 113.93 },
  meituan: { city: "Beijing", region: "China", lat: 39.98, lng: 116.49 },
  sakana: { city: "Tokyo", region: "Japan", lat: 35.68, lng: 139.76 },
  stepfun: { city: "Shanghai", region: "China", lat: 31.2, lng: 121.44 },
  openbmb: { city: "Beijing", region: "China", lat: 40.0, lng: 116.33 },
  thinkingmachines: { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.4 },
  sarvam: { city: "Bengaluru", region: "India", lat: 12.97, lng: 77.59 },
  writer: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  trendyol: { city: "Istanbul", region: "Türkiye", lat: 41.08, lng: 29.01 },
  aisingapore: { city: "Singapore", region: "Singapore", lat: 1.3, lng: 103.78 },
  inclusionai: { city: "Hangzhou (Ant Group)", region: "China", lat: 30.27, lng: 120.12 },
  sdaia: { city: "Riyadh", region: "Saudi Arabia", lat: 24.71, lng: 46.68 },
  poolside: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  upstage: { city: "Pangyo, Seongnam", region: "South Korea", lat: 37.4, lng: 127.11 },
  deepreinforce: { city: "San Jose", region: "United States", lat: 37.34, lng: -121.89 },
  "swiss-ai": { city: "Zurich (ETH / EPFL)", region: "Switzerland", lat: 47.38, lng: 8.55 },
  // Looked up September 2026: published HQ first, registered business address when no HQ is published.
  "merge-gateway": { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  edenai: { city: "Lyon", region: "Europe", lat: 45.76, lng: 4.85 },
  kilo: { city: "San Francisco", region: "United States", lat: 37.79, lng: -122.4 },
  "llmgateway-providers": { city: "Lewes, DE (registered)", region: "United States", lat: 38.77, lng: -75.14 },
  zenmux: { city: "Sunnyvale", region: "United States", lat: 37.37, lng: -122.04 },
  "novita-ai": { city: "San Francisco", region: "United States", lat: 37.77, lng: -122.42 },
  anyapi: { city: "New York", region: "United States", lat: 40.75, lng: -73.99 },
  nearai: { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.41 },
  abacus: { city: "San Francisco", region: "United States", lat: 37.78, lng: -122.41 },
  crusoe: { city: "Denver", region: "United States", lat: 39.74, lng: -104.99 },
  gmicloud: { city: "Mountain View", region: "United States", lat: 37.39, lng: -122.08 },
  inference: { city: "San Francisco", region: "United States", lat: 37.77, lng: -122.41 },
  "io-net": { city: "New York", region: "United States", lat: 40.72, lng: -74.0 },
  lmstudio: { city: "Brooklyn, NY", region: "United States", lat: 40.7, lng: -73.97 },
  "hpc-ai": { city: "Singapore", region: "Singapore", lat: 1.3, lng: 103.8 },
  tensorx: { city: "Dublin", region: "Europe", lat: 53.35, lng: -6.26 },
  aiand: { city: "Yokohama", region: "Japan", lat: 35.46, lng: 139.63 },
};

const byName: Record<string, string> = {
  openai: "openai",
  anthropic: "anthropic",
  google: "google",
  "xai": "xai",
  "x.ai": "xai",
  meta: "meta",
  groq: "groq",
  cerebras: "cerebras",
  "fireworks ai": "fireworks",
  together: "together",
  "together ai": "together",
  perplexity: "perplexity",
  nvidia: "nvidia",
  databricks: "databricks",
  "amazon bedrock": "amazon-bedrock",
  azure: "azure",
  "github copilot": "github-copilot",
  huggingface: "huggingface",
  cohere: "cohere",
  mistral: "mistral",
  "ai21 labs": "ai21",
  deepseek: "deepseek",
  alibaba: "alibaba",
  "alibaba (china)": "alibaba-cn",
  "moonshot ai": "moonshot",
  moonshotai: "moonshotai",
  zhipuai: "zhipuai",
  "z.ai": "zai",
  baidu: "baidu",
  minimax: "minimax",
};

export function locate(id: string, name: string): Place | null {
  const key = id.toLowerCase();
  if (places[key]) return places[key];
  const alias = byName[name.trim().toLowerCase()];
  return alias ? places[alias] ?? null : null;
}
